" A collection of language packs for Vim.
" It won't affect your startup time, as scripts are loaded only on demand*.
" It installs and updates 120+ times faster than the 598 packages it consists of.
" It is also more secure (scripts loaded for every filetype are generated by vim-polyglot)
" Best syntax and indentation support (no other features). Hand-selected language packs.
" Automatically detects indentation (includes performance-optimized version of vim-sleuth, can be disabled)
Plug 'sheerun/vim-polyglot'
